# Configuration for dependency-review-action
# Documentation: https://github.com/actions/dependency-review-action

# List of packages that should never be allowed
# run the test locally with `npm run security:check`
deny-packages:
  # These are packages from the npm supply chain attack (Sept 2025)
  # Source: https://socket.dev/blog/npm-author-qix-compromised-in-major-supply-chain-attack
  - pkg:npm/backslash@0.2.1
  - pkg:npm/chalk@5.6.1
  - pkg:npm/chalk-template@1.1.1
  - pkg:npm/color-convert@3.1.1
  - pkg:npm/color-name@2.0.1
  - pkg:npm/color-string@2.1.1
  - pkg:npm/wrap-ansi@9.0.1
  - pkg:npm/supports-hyperlinks@4.1.1
  - pkg:npm/strip-ansi@7.1.1
  - pkg:npm/slice-ansi@7.1.1
  - pkg:npm/simple-swizzle@0.2.3
  - pkg:npm/is-arrayish@0.3.3
  - pkg:npm/error-ex@1.3.3
  - pkg:npm/has-ansi@6.0.1
  - pkg:npm/ansi-regex@6.2.1
  - pkg:npm/ansi-styles@6.2.2
  - pkg:npm/supports-color@10.2.1
  - pkg:npm/proto-tinker-wc@1.8.7
  - pkg:npm/debug@4.4.2
  # These are packages from the S1ngularity/nx attack
  # https://www.aikido.dev/blog/s1ngularity-nx-attackers-strike-again
  - pkg:npm/@ahmedhfarag/ngx-perfect-scrollbar@20.0.20
  - pkg:npm/@ahmedhfarag/ngx-virtual-scroller@4.0.4
  - pkg:npm/@art-ws/common@2.0.28
  - pkg:npm/@art-ws/config-eslint@2.0.4
  - pkg:npm/@art-ws/config-eslint@2.0.5
  - pkg:npm/@art-ws/config-ts@2.0.7
  - pkg:npm/@art-ws/config-ts@2.0.8
  - pkg:npm/@art-ws/db-context@2.0.24
  - pkg:npm/@art-ws/di@2.0.28
  - pkg:npm/@art-ws/di@2.0.32
  - pkg:npm/@art-ws/di-node@2.0.13
  - pkg:npm/@art-ws/eslint@1.0.5
  - pkg:npm/@art-ws/eslint@1.0.6
  - pkg:npm/@art-ws/fastify-http-server@2.0.24
  - pkg:npm/@art-ws/fastify-http-server@2.0.27
  - pkg:npm/@art-ws/http-server@2.0.21
  - pkg:npm/@art-ws/http-server@2.0.25
  - pkg:npm/@art-ws/openapi@0.1.9
  - pkg:npm/@art-ws/openapi@0.1.12
  - pkg:npm/@art-ws/package-base@1.0.5
  - pkg:npm/@art-ws/package-base@1.0.6
  - pkg:npm/@art-ws/prettier@1.0.5
  - pkg:npm/@art-ws/prettier@1.0.6
  - pkg:npm/@art-ws/slf@2.0.15
  - pkg:npm/@art-ws/slf@2.0.22
  - pkg:npm/@art-ws/ssl-info@1.0.9
  - pkg:npm/@art-ws/ssl-info@1.0.10
  - pkg:npm/@art-ws/web-app@1.0.3
  - pkg:npm/@art-ws/web-app@1.0.4
  - pkg:npm/@crowdstrike/commitlint@8.1.1
  - pkg:npm/@crowdstrike/commitlint@8.1.2
  - pkg:npm/@crowdstrike/falcon-shoelace@0.4.1
  - pkg:npm/@crowdstrike/falcon-shoelace@0.4.2
  - pkg:npm/@crowdstrike/foundry-js@0.19.1
  - pkg:npm/@crowdstrike/foundry-js@0.19.2
  - pkg:npm/@crowdstrike/glide-core@0.34.2
  - pkg:npm/@crowdstrike/glide-core@0.34.3
  - pkg:npm/@crowdstrike/logscale-dashboard@1.205.1
  - pkg:npm/@crowdstrike/logscale-dashboard@1.205.2
  - pkg:npm/@crowdstrike/logscale-file-editor@1.205.1
  - pkg:npm/@crowdstrike/logscale-file-editor@1.205.2
  - pkg:npm/@denoland/denort@0.2.0
  - pkg:npm/@denoland/denort@0.2.1
  - pkg:npm/@denoland/ts-morph@23.1.0
  - pkg:npm/@denoland/ts-morph@23.1.1
  - pkg:npm/@floriancornu/ngx-toastr@19.0.1
  - pkg:npm/@floriancornu/ngx-toastr@19.0.2
  - pkg:npm/@fluent-wallet/wallet-connect@1.0.2
  - pkg:npm/@fluent-wallet/wallet-connect@1.0.3
  - pkg:npm/@freyja-ui/fast@0.0.15
  - pkg:npm/@freyja-ui/fast@0.0.16
  - pkg:npm/@freyja-ui/store@0.2.4
  - pkg:npm/@freyja-ui/store@0.2.5
  - pkg:npm/@graphprotocol/graph-ts-wasm@0.36.1
  - pkg:npm/@graphprotocol/graph-ts-wasm@0.36.2
  - pkg:npm/@launchbox-ui/block-text@5.2.1
  - pkg:npm/@launchbox-ui/block-text@5.2.2
  - pkg:npm/@launchbox-ui/heading@5.2.1
  - pkg:npm/@launchbox-ui/heading@5.2.2
  - pkg:npm/@launchbox-ui/popover-content@5.2.1
  - pkg:npm/@launchbox-ui/popover-content@5.2.2
  - pkg:npm/@launchbox-ui/snackbar@5.2.1
  - pkg:npm/@launchbox-ui/snackbar@5.2.2
  - pkg:npm/@launchbox-ui/tabs@5.2.1
  - pkg:npm/@launchbox-ui/tabs@5.2.2
  - pkg:npm/@launchbox-ui/tokens@5.2.1
  - pkg:npm/@launchbox-ui/tokens@5.2.2
  - pkg:npm/@mantine-post/dates@7.13.6
  - pkg:npm/@mantine-post/tiptap@7.13.6
  - pkg:npm/@mysecure/bridge@1.0.2
  - pkg:npm/@mysecure/rpc-library@0.0.7
  - pkg:npm/@n3dst4/easings-js@2.0.3
  - pkg:npm/@n3dst4/easings-js@2.0.4
  - pkg:npm/@osbrnio/commitlint@2.12.0
  - pkg:npm/@osbrnio/commitlint@2.12.1
  - pkg:npm/@osbrnio/glide@3.32.0
  - pkg:npm/@osbrnio/glide@3.32.1
  - pkg:npm/@osbrnio/jest-utils@16.0.0
  - pkg:npm/@osbrnio/jest-utils@16.0.1
  - pkg:npm/@osbrnio/lz-string@1.6.1
  - pkg:npm/@osbrnio/lz-string@1.6.2
  - pkg:npm/@osbrnio/prettier@4.6.6
  - pkg:npm/@osbrnio/prettier@4.6.7
  - pkg:npm/@oslojs/asn1@0.2.1
  - pkg:npm/@oslojs/crypto@1.0.1
  - pkg:npm/@oslojs/encoding@1.1.1
  - pkg:npm/@oslojs/jwt@0.1.1
  - pkg:npm/@penguin-statistics/widget@8.1.6
  - pkg:npm/@penguin-statistics/widget@8.1.7
  - pkg:npm/@pichipay-wallet/wallet-connect@1.0.3
  - pkg:npm/@pm2/agent@2.0.5
  - pkg:npm/@pm2/agent@2.0.6
  - pkg:npm/@pm2/agent@2.0.7
  - pkg:npm/@pm2/agent@2.0.8
  - pkg:npm/@pm2/io@6.0.2
  - pkg:npm/@pm2/io@6.0.3
  - pkg:npm/@pm2/js-api@0.8.1
  - pkg:npm/@pm2/js-api@0.8.2
  - pkg:npm/@pm2/pm2-version-check@1.0.5
  - pkg:npm/@pm2/pm2-version-check@1.0.6
  - pkg:npm/@rxnt/ui-microservice@2.5.18
  - pkg:npm/@rxnt/ui-microservice@2.5.19
  - pkg:npm/@rxnt/ui-microservice@2.5.20
  - pkg:npm/@rxnt/ui-microservice@2.5.21
  - pkg:npm/@valor/launchpad@19.0.1
  - pkg:npm/@valor/launchpad@19.0.2
  - pkg:npm/@valor/ngx-bootstrap@1.0.2
  - pkg:npm/@valor/ngx-bootstrap@1.0.3
  - pkg:npm/angular-sortablejs@12.0.1
  - pkg:npm/angular-sortablejs@12.0.2
  - pkg:npm/angular2-csv@0.2.10
  - pkg:npm/angular2-toaster@11.0.2
  - pkg:npm/angular2-toaster@11.0.3
  - pkg:npm/aop-node@1.0.3
  - pkg:npm/aop-node@1.0.4
  - pkg:npm/baconjs@3.0.20
  - pkg:npm/baconjs@3.0.21
  - pkg:npm/bedrock-dts-generator@3.0.18
  - pkg:npm/bedrock-dts-generator@3.0.19
  - pkg:npm/bnc-assist@0.9.8
  - pkg:npm/bnc-assist@0.9.9
  - pkg:npm/build-crowdstrike@14.3.1
  - pkg:npm/build-crowdstrike@14.3.2
  - pkg:npm/buildium-app-server@0.0.36
  - pkg:npm/buildium-app-server@0.0.37
  - pkg:npm/buildium-package-template@0.0.29
  - pkg:npm/buildium-package-template@0.0.30
  - pkg:npm/buildkit-crowdstrike@11.0.2
  - pkg:npm/buildkit-crowdstrike@11.0.3
  - pkg:npm/bump-version-git-publish@1.0.1
  - pkg:npm/bump-version-git-publish@1.0.2
  - pkg:npm/callbackjs@0.3.1
  - pkg:npm/canvas-datagrid@0.5.1
  - pkg:npm/canvas-datagrid@0.5.2
  - pkg:npm/canvas-datagrid@0.5.3
  - pkg:npm/cfn-output-exporter-lambda@1.2.3
  - pkg:npm/cfn-output-exporter-lambda@1.2.4
  - pkg:npm/component-type@1.2.3
  - pkg:npm/component-type@1.2.4
  - pkg:npm/css-type-js@2.7.16
  - pkg:npm/css-type-js@2.7.17
  - pkg:npm/csv-parser@3.1.1
  - pkg:npm/csv-parser@3.1.2
  - pkg:npm/data-struct-js@1.2.2
  - pkg:npm/data-struct-js@1.2.3
  - pkg:npm/dc-vis@3.0.13
  - pkg:npm/dc-vis@3.0.14
  - pkg:npm/design-system-a@1.0.20
  - pkg:npm/design-system-a@1.0.21
  - pkg:npm/design-system-b@1.0.20
  - pkg:npm/design-system-b@1.0.21
  - pkg:npm/design-system-d@1.0.16
  - pkg:npm/design-system-d@1.0.17
  - pkg:npm/file-type@19.6.0
  - pkg:npm/file-type@19.6.1
  - pkg:npm/fk-lib@2.0.5
  - pkg:npm/flowify@2.2.2
  - pkg:npm/flowify@2.2.3
  - pkg:npm/glide-core-crowdstrike@13.7.1
  - pkg:npm/glide-core-crowdstrike@13.7.2
  - pkg:npm/gray-matter@4.2.1
  - pkg:npm/hll-stream@1.0.6
  - pkg:npm/hll-stream@1.0.7
  - pkg:npm/import-regex@1.1.1
  - pkg:npm/import-regex@1.1.2
  - pkg:npm/import-regex@1.1.3
  - pkg:npm/is@4.0.1
  - pkg:npm/is@4.0.2
  - pkg:npm/json-server@1.0.0-rc.2
  - pkg:npm/json-server@1.0.0-rc.3
  - pkg:npm/json-server@1.0.0-rc.4
  - pkg:npm/liferay-npm-bundler-loader-css-loader@4.5.2
  - pkg:npm/liferay-npm-bundler-plugin-css-files@2.31.1
  - pkg:npm/localhostess-cli@0.1.4
  - pkg:npm/localhostess-cli@0.1.5
  - pkg:npm/logscale@4.1.1
  - pkg:npm/logscale@4.1.2
  - pkg:npm/logscale-js-client@3.1.1
  - pkg:npm/logscale-js-client@3.1.2
  - pkg:npm/lw-admin-hub-main@1.0.10
  - pkg:npm/lw-admin-hub-main@1.0.11
  - pkg:npm/marked@15.0.4
  - pkg:npm/mcp-knowledge-graph@1.2.1
  - pkg:npm/mobioffice-cli@1.0.3
  - pkg:npm/monorepo-next@13.0.1
  - pkg:npm/monorepo-next@13.0.2
  - pkg:npm/mstate-angular@0.4.4
  - pkg:npm/mstate-cli@0.4.7
  - pkg:npm/mstate-dev-react@1.1.1
  - pkg:npm/mstate-react@1.6.5
  - pkg:npm/ng2-file-upload@7.0.2
  - pkg:npm/ng2-file-upload@7.0.3
  - pkg:npm/ng2-file-upload@8.0.1
  - pkg:npm/ng2-file-upload@8.0.2
  - pkg:npm/ng2-file-upload@8.0.3
  - pkg:npm/ng2-file-upload@9.0.1
  - pkg:npm/ngx-bootstrap@18.1.4
  - pkg:npm/ngx-bootstrap@19.0.3
  - pkg:npm/ngx-bootstrap@19.0.4
  - pkg:npm/ngx-bootstrap@20.0.3
  - pkg:npm/ngx-bootstrap@20.0.4
  - pkg:npm/ngx-bootstrap@20.0.5
  - pkg:npm/ngx-color@10.0.1
  - pkg:npm/ngx-color@10.0.2
  - pkg:npm/ngx-toastr@19.0.1
  - pkg:npm/ngx-toastr@19.0.2
  - pkg:npm/ngx-trend@8.0.1
  - pkg:npm/ngx-ws@1.1.5
  - pkg:npm/ngx-ws@1.1.6
  - pkg:npm/oradm-to-gql@35.0.14
  - pkg:npm/oradm-to-gql@35.0.15
  - pkg:npm/oradm-to-sqlz@1.1.2
  - pkg:npm/ove-auto-annotate@0.0.9
  - pkg:npm/pm2-gelf-json@1.0.4
  - pkg:npm/pm2-gelf-json@1.0.5
  - pkg:npm/printjs-rpk@1.6.1
  - pkg:npm/react-complaint-image@0.0.32
  - pkg:npm/react-jsonschema-form-conditionals@0.3.18
  - pkg:npm/remark-preset-lint-crowdstrike@4.0.1
  - pkg:npm/remark-preset-lint-crowdstrike@4.0.2
  - pkg:npm/rxnt-authentication@0.0.3
  - pkg:npm/rxnt-authentication@0.0.4
  - pkg:npm/rxnt-authentication@0.0.5
  - pkg:npm/rxnt-authentication@0.0.6
  - pkg:npm/rxnt-healthchecks-nestjs@1.0.2
  - pkg:npm/rxnt-healthchecks-nestjs@1.0.3
  - pkg:npm/rxnt-healthchecks-nestjs@1.0.4
  - pkg:npm/rxnt-healthchecks-nestjs@1.0.5
  - pkg:npm/rxnt-kue@1.0.4
  - pkg:npm/rxnt-kue@1.0.5
  - pkg:npm/rxnt-kue@1.0.6
  - pkg:npm/rxnt-kue@1.0.7
  - pkg:npm/swc-plugin-component-annotate@1.9.1
  - pkg:npm/swc-plugin-component-annotate@1.9.2
  - pkg:npm/tbssnch@1.0.2
  - pkg:npm/teselagen-interval-tree@1.1.2
  - pkg:npm/tg-client-query-builder@2.14.4
  - pkg:npm/tg-client-query-builder@2.14.5
  - pkg:npm/tg-redbird@1.3.1
  - pkg:npm/tg-seq-gen@1.0.9
  - pkg:npm/tg-seq-gen@1.0.10
  - pkg:npm/thangved-react-grid@1.0.3
  - pkg:npm/ts-gaussian@3.0.5
  - pkg:npm/ts-gaussian@3.0.6
  - pkg:npm/ts-imports@1.0.1
  - pkg:npm/ts-imports@1.0.2
  - pkg:npm/tvi-cli@0.1.5
  - pkg:npm/ve-bamreader@0.2.6
  - pkg:npm/ve-editor@1.0.1
  - pkg:npm/verror-extra@6.0.1
  - pkg:npm/voip-callkit@1.0.2
  - pkg:npm/voip-callkit@1.0.3
  - pkg:npm/wdio-web-reporter@0.1.3
  - pkg:npm/yargs-help-output@5.0.3
  - pkg:npm/yoo-styles@6.0.326
  # These are packages from the tinycolor supply chain attack (Sept 2025)
  # Source: https://socket.dev/blog/tinycolor-supply-chain-attack-affects-40-packages
  - pkg:npm/angulartics2@14.1.2
  - pkg:npm/@ctrl/deluge@7.2.2
  - pkg:npm/@ctrl/golang-template@1.4.3
  - pkg:npm/@ctrl/magnet-link@4.0.4
  - pkg:npm/@ctrl/ngx-codemirror@7.0.2
  - pkg:npm/@ctrl/ngx-csv@6.0.2
  - pkg:npm/@ctrl/ngx-emoji-mart@9.2.2
  - pkg:npm/@ctrl/ngx-rightclick@4.0.2
  - pkg:npm/@ctrl/qbittorrent@9.7.2
  - pkg:npm/@ctrl/react-adsense@2.0.2
  - pkg:npm/@ctrl/shared-torrent@6.3.2
  - pkg:npm/@ctrl/tinycolor@4.1.1
  - pkg:npm/@ctrl/tinycolor@4.1.2
  - pkg:npm/@ctrl/torrent-file@4.1.2
  - pkg:npm/@ctrl/transmission@7.3.1
  - pkg:npm/@ctrl/ts-base32@4.0.2
  - pkg:npm/encounter-playground@0.0.5
  - pkg:npm/json-rules-engine-simplified@0.2.1
  - pkg:npm/json-rules-engine-simplified@0.2.4
  - pkg:npm/koa2-swagger-ui@5.11.1
  - pkg:npm/koa2-swagger-ui@5.11.2
  - pkg:npm/@nativescript-community/gesturehandler@2.0.35
  - pkg:npm/@nativescript-community/sentry@4.6.43
  - pkg:npm/@nativescript-community/text@1.6.13
  - pkg:npm/@nativescript-community/ui-collectionview@6.0.6
  - pkg:npm/@nativescript-community/ui-drawer@0.1.30
  - pkg:npm/@nativescript-community/ui-image@4.5.6
  - pkg:npm/@nativescript-community/ui-material-bottomsheet@7.2.72
  - pkg:npm/@nativescript-community/ui-material-core@7.2.76
  - pkg:npm/@nativescript-community/ui-material-core-tabs@7.2.76
  - pkg:npm/react-complaint-image@0.0.35
  - pkg:npm/react-jsonschema-form-conditionals@0.3.21
  - pkg:npm/react-jsonschema-form-extras@1.0.4

# Additional settings for more strict checking
warn-only: false
