language: node_js
sudo: required
branches:
  only:
  - main
  - prod-beta
notifications:
  email: false
node_js:
  - '16'
install:
  - npm install
script:
  - npm run travis:verify
  - npx codecov
after_success:
  - curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
env:
  global:
  - REPO="git@github.com:RedHatInsights/image-builder-frontend-build"
  - REPO_DIR="image-builder-frontend-build"
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
